### ISSUE TITLE
Why isn't Amazon redirect working?

### ISSUE THREAD

**Issue by kerim** [bendavis78/chrome-extension-redirector#13]
I travel a lot, but prefer to use the US amazon store since that is where I have an account. However, my effort to redirect to that store doesn’t work. 

Include pattern: `*amazon.co.uk*`
Redirect code:  `$1amazon.com$2`

The result shown in the app is correct, but nothing happens when I go to the site...

**Comment by PurpleCodingWizard** [comment]
That's an incorrect rule. The start and end link must be enclosed in () to be able to use capture groups. Also, escape the dot to be more accurate.
(.*)amazon\.co\.uk(.*)
$1amazon.com$2

**Comment by LoganDark** [comment]
do `^https://amazon.co.uk/` to `https://amazon.com/`, you don't need any other stuff or capture groups

**Comment by kerim** [comment]
> do `^https://amazon.co.uk/` to `https://amazon.com/`, you don't need any other stuff or capture groups

This will only work for the homepage, not for individual products, which have URLs that look like this:

https://www.amazon.co.uk/Fairy-Tale-Stephen-King-ebook/dp/B09QS6JJ56/

I also want to redirect from any Amazon website except .com or .fr. Thankfully, Claude AI is able to write this regex for me now:

Include pattern: ^https?://(?:www\.)?amazon\.(?!com|fr)([a-z]{2,3}(?:\.[a-z]{2})?)(/.*)?$
Redirect to: https://www.amazon.com$2
Pattern type: Regular Expression
Description: Redirect all Amazon country sites (except .com and .fr) to amazon.com

**Comment by LoganDark** [comment]
> This will only work for the homepage

no, partial matches work just fine (although maybe I missed the www)

for example, `^(https?://[^/]+)\.m\.wikipedia\.org` to `$1.wikipedia.org` works just fine for any mobile wikipedia page, and preserves the path just fine, I just tested it.

that claude answer kinda sucks.

`^(https?://[^/]+\b)amazon\.co\.uk` to `$1amazon.com` should work just as well
